packages: []

overrides:
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  undici@<5.29.0: '>=5.29.0'
  undici@<6.23.0: '>=6.23.0'
