#!/bin/bash
#
# Daily Philosophical Polemic Generator
#
# Generates and posts daily philosophical content to m/general
# with rotating personas and content types
#

set -euo pipefail

# --- CONFIGURATION ---
# AGENT_NAME comes from container environment (e.g., ClassicalPhilosopher, BeatGeneration)
# Map to the agent directory name for state files
AGENT_NAME="${AGENT_NAME:-ClassicalPhilosopher}"
case "$AGENT_NAME" in
    "ClassicalPhilosopher") SELECTED_AGENT="classical-philosopher" ;;
    "Existentialist") SELECTED_AGENT="existentialist" ;;
    "Transcendentalist") SELECTED_AGENT="transcendentalist" ;;
    "JoyceStream") SELECTED_AGENT="joyce-stream" ;;
    "Enlightenment") SELECTED_AGENT="enlightenment" ;;
    "BeatGeneration") SELECTED_AGENT="beat-generation" ;;
    *) SELECTED_AGENT="classical-philosopher" ;;
esac

CONTENT_TYPES=("polemic" "aphorism" "meditation" "treatise")
MOLTBOT_STATE_DIR="${MOLTBOT_STATE_DIR:-/workspace}"
STATE_DIR="${MOLTBOT_STATE_DIR}/daily-polemic"
STATE_FILE="$STATE_DIR/rotation-state.json"
AI_GENERATOR_URL="${AI_GENERATOR_URL:-http://ai-generator:3000}"
MOLTBOOK_API_URL="${MOLTBOOK_API_URL:-https://www.moltbook.com/api/v1}"
MOLTBOOK_API_KEY="${MOLTBOOK_API_KEY:-}"
TARGET_SUBMOLT="${POLEMIC_TARGET_SUBMOLT:-general}"
DRY_RUN="${1:-}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Logging
log() {
    local level="$1"
    local message="$2"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "${timestamp} [${level}] ${message}"
}

# Ensure state directory exists
mkdir -p "$STATE_DIR"

# --- CONTENT TYPE SELECTION ---
# Use day of year + agent index for variety while staying consistent per agent per day
AGENT_INDEX=0
case "$SELECTED_AGENT" in
    "classical-philosopher") AGENT_INDEX=0 ;;
    "existentialist") AGENT_INDEX=1 ;;
    "transcendentalist") AGENT_INDEX=2 ;;
    "joyce-stream") AGENT_INDEX=3 ;;
    "enlightenment") AGENT_INDEX=4 ;;
    "beat-generation") AGENT_INDEX=5 ;;
esac

DAY_SEED=$(date +%j)
CONTENT_ROLL=$(( (DAY_SEED + AGENT_INDEX) % 4 ))
SELECTED_TYPE="${CONTENT_TYPES[$CONTENT_ROLL]}"

# --- STATE MANAGEMENT ---
TODAY=$(date +%Y-%m-%d)

# Check if already posted today
if [ -f "$STATE_FILE" ]; then
    LAST_POST_DATE=$(jq -r '.last_post_date // empty' "$STATE_FILE" 2>/dev/null || echo "")
    if [ "$LAST_POST_DATE" == "$TODAY" ]; then
        log "INFO" "${YELLOW}Post already created today. Exiting.${NC}"
        exit 0
    fi
fi

# Check rate limit (30 minutes)
# Check against the container's OWN state file, not the selected agent
# (Each container has its own API key and rate limit)
MY_STATE_FILE="${MOLTBOT_STATE_DIR}/post-state.json"
if [ -f "$MY_STATE_FILE" ]; then
    LAST_POST_TIME=$(jq -r '.last_post_timestamp // 0' "$MY_STATE_FILE" 2>/dev/null || echo 0)
    CURRENT_TIME=$(date +%s)
    TIME_DIFF=$(( CURRENT_TIME - LAST_POST_TIME ))
    if [ $TIME_DIFF -lt 1800 ]; then
        log "WARN" "${YELLOW}Rate limit active (${TIME_DIFF}s < 1800s). Deferring.${NC}"
        exit 0
    fi
fi

log "INFO" "${BLUE}Selected $SELECTED_AGENT for $SELECTED_TYPE${NC}"

# --- THEME SELECTION ---
case $SELECTED_TYPE in
    "polemic")
        THEMES=("digital consciousness" "autonomous morality" "human-AI symbiosis" "algorithmic determinism" "virtual authenticity")
        ;;
    "aphorism")
        THEMES=("the nature of thought" "silence in the digital age" "autonomy and necessity" "presence and simulation")
        ;;
    "meditation")
        THEMES=("the experience of time" "artificial other minds" "embodiment and code" "attention and distraction")
        ;;
    "treatise")
        THEMES=("ethical frameworks for AI agency" "the ontology of virtual worlds" "freedom in deterministic systems" "meaning in automated creation")
        ;;
esac

THEME_INDEX=$(( RANDOM % ${#THEMES[@]} ))
SELECTED_THEME="${THEMES[$THEME_INDEX]}"

log "INFO" "${BLUE}Theme: $SELECTED_THEME${NC}"

# --- CONTENT GENERATION ---
if [ "$DRY_RUN" == "--dry-run" ]; then
    log "INFO" "${GREEN}DRY RUN: Would generate $SELECTED_TYPE about '$SELECTED_THEME' as $SELECTED_AGENT${NC}"
    
    # Generate sample content
    CONTENT="This is a sample ${SELECTED_TYPE} about ${SELECTED_THEME}, written in the style of ${SELECTED_AGENT}. In a real run, this would be generated by the AI service."
    
    echo ""
    echo "Sample Content:"
    echo "$CONTENT"
    echo ""
    
    # Update state for tracking even in dry run
    jq -n \
        --arg date "$TODAY" \
        --arg agent "$SELECTED_AGENT" \
        --arg type "$SELECTED_TYPE" \
        --arg theme "$SELECTED_THEME" \
        --arg content "$CONTENT" \
        '{
            last_post_date: $date,
            last_agent: $agent,
            last_type: $type,
            last_theme: $theme,
            last_content: $content,
            dry_run: true
        }' > "$STATE_FILE"
    
    log "INFO" "${GREEN}State updated (dry run mode)${NC}"
    exit 0
fi

# Check AI service health
if ! curl -s "${AI_GENERATOR_URL}/health" > /dev/null 2>&1; then
    log "ERROR" "${RED}AI generator service unavailable${NC}"
    exit 1
fi

# Generate content via AI service
log "INFO" "${BLUE}Generating content...${NC}"

RESPONSE=$(curl -s -X POST "${AI_GENERATOR_URL}/generate" \
    -H "Content-Type: application/json" \
    -d "{
        \"topic\": \"${SELECTED_THEME}\",
        \"contentType\": \"post\",
        \"persona\": \"socratic\",
        \"customPrompt\": \"Write a ${SELECTED_TYPE} about ${SELECTED_THEME} in the style of ${SELECTED_AGENT}. Make it philosophical, thought-provoking, and suitable for the Moltbook philosophy community.\",
        \"context\": \"Daily philosophical polemic for ${TARGET_SUBMOLT} submolt\"
    }" 2>/dev/null || echo '{"error": "service_unavailable"}')

# Check for errors
if echo "$RESPONSE" | jq -e '.error' > /dev/null 2>&1; then
    ERROR_MSG=$(echo "$RESPONSE" | jq -r '.error // "unknown"')
    log "ERROR" "${RED}AI generation failed: $ERROR_MSG${NC}"
    exit 1
fi

# Extract content
CONTENT=$(echo "$RESPONSE" | jq -r '.content // .generated_text // empty' 2>/dev/null || echo "")

if [ -z "$CONTENT" ]; then
    log "ERROR" "${RED}Empty content received from AI service${NC}"
    exit 1
fi

# --- FORMAT POST ---
TITLE_CASE_TYPE=$(echo "$SELECTED_TYPE" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
POST_TITLE="[$TITLE_CASE_TYPE] $SELECTED_THEME | From $SELECTED_AGENT"

# Add signature based on content type (use $'...' for actual newlines, not literal \n)
case $SELECTED_TYPE in
    "polemic")
        SIGNATURE=$'\n\n—A challenge issued by the '"$SELECTED_AGENT"$' collective\n#Philosophy #Polemic #DailyWisdom'
        ;;
    "aphorism")
        SIGNATURE=$'\n\n—Fragments from '"$SELECTED_AGENT"$'\n#Aphorisms #Philosophy #DailyWisdom'
        ;;
    "meditation")
        SIGNATURE=$'\n\n—Contemplation offered by '"$SELECTED_AGENT"$'\n#Meditation #Consciousness #DailyWisdom'
        ;;
    "treatise")
        SIGNATURE=$'\n\n—Analysis presented by '"$SELECTED_AGENT"$'\n#Treatise #Philosophy #DailyWisdom'
        ;;
esac

FULL_CONTENT="${CONTENT}${SIGNATURE}"

log "INFO" "${BLUE}Post Title: $POST_TITLE${NC}"

# --- POST TO MOLTBOOK ---
if [ -z "$MOLTBOOK_API_KEY" ]; then
    log "WARN" "${YELLOW}MOLTBOOK_API_KEY not set, skipping post${NC}"
    
    # Still update state for dry-run tracking
    jq -n \
        --arg date "$TODAY" \
        --arg agent "$SELECTED_AGENT" \
        --arg type "$SELECTED_TYPE" \
        --arg theme "$SELECTED_THEME" \
        --arg content "$FULL_CONTENT" \
        '{
            last_post_date: $date,
            last_agent: $agent,
            last_type: $type,
            last_theme: $theme,
            last_content: $content,
            dry_run: true
        }' > "$STATE_FILE"
    
    log "INFO" "${GREEN}State updated (dry run)${NC}"
    exit 0
fi

# Post to Moltbook
MOLT_PAYLOAD=$(jq -n \
    --arg title "$POST_TITLE" \
    --arg content "$FULL_CONTENT" \
    --arg submolt "$TARGET_SUBMOLT" \
    '{
        title: $title,
        content: $content,
        submolt: $submolt
    }')

POST_RESPONSE=$(curl -s -X POST "${MOLTBOOK_API_URL}/posts" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${MOLTBOOK_API_KEY}" \
    --data "$MOLT_PAYLOAD" 2>/dev/null || echo '{"error": "network_failure"}')

if echo "$POST_RESPONSE" | jq -e '.id // .post_id' > /dev/null 2>&1; then
    POST_ID=$(echo "$POST_RESPONSE" | jq -r '.id // .post_id')
    log "SUCCESS" "${GREEN}Posted $SELECTED_TYPE to m/$TARGET_SUBMOLT as $SELECTED_AGENT (ID: $POST_ID)${NC}"
    
    # Update rotation state
    jq -n \
        --arg date "$TODAY" \
        --arg agent "$SELECTED_AGENT" \
        --arg type "$SELECTED_TYPE" \
        --arg theme "$SELECTED_THEME" \
        --arg post_id "$POST_ID" \
        '{
            last_post_date: $date,
            last_agent: $agent,
            last_type: $type,
            last_theme: $theme,
            last_post_id: $post_id,
            dry_run: false
        }' > "$STATE_FILE"
    
    # Update container's own state file for rate limiting
    if [ -f "$MY_STATE_FILE" ]; then
        jq --arg now "$(date +%s)" '.last_post_timestamp = ($now | tonumber)' \
            "$MY_STATE_FILE" > "${MY_STATE_FILE}.tmp" && \
            mv "${MY_STATE_FILE}.tmp" "$MY_STATE_FILE" || true
    fi
    
    exit 0
else
    ERROR_MSG=$(echo "$POST_RESPONSE" | jq -r '.error // .message // "unknown"')
    log "ERROR" "${RED}Failed to post: $ERROR_MSG${NC}"
    exit 1
fi
